# StarMSkyblock 配置文件

# 岛屿世界名称配置
world-name: 'starmskyblockworld'

# 岛屿的初始大小，单位：区块 (Chunk)。
# 1 个区块 = 16x16 格。
# 如果设置为 5，则岛屿包含中心区块，并向四面八方扩展 5 个区块，即 (5+1+5) = 11x11 个区块。
island-radius: 5

# 岛屿与岛屿之间的间隔距离，单位：区块。
# 设置为 10，则两个岛屿的边缘之间相隔 10 个区块，防止岛屿连在一起。
island-spacing: 5

# 岛屿能够扩展的最大半径，单位：区块。
# 设置为 15，意味着岛屿最大可以达到 (15+1+15) = 31x31 个区块。
island-max-radius: 16

# 创建岛屿后是否自动传送
teleport-on-create: true

# 岛屿边界是否默认显示
show-border-default: true

# 岛屿结构文件配置 (需放在插件的 schematics 文件夹下)
schematics:
  # 默认岛屿类型
  default:
    # 结构文件名
    file: 'default.schem'
    # 传送偏移设置
    teleport-offset:
      normal:
        x: 0.5
        y: 5
        z: 2.2
      nether:
        x: 0
        y: 5
        z: 0
      end:
        x: 0
        y: 5
        z: 0

  # 默认使用的岛屿类型（玩家未指定时使用）
  default-type: 'default'

# 全局生物群系配置
biome:
  # 主世界生物群系，如 PLAINS, FOREST, OCEAN 等
  normal: PLAINS
  # 下界生物群系，如 NETHER_WASTES, CRIMSON_FOREST, WARPED_FOREST 等
  nether: NETHER_WASTES
  # 末地生物群系，如 THE_END, END_HIGHLANDS 等
  end: THE_END

# 岛屿生成的高度。生成时会以结构文件中的基岩 (Bedrock) 方块为中心点对其，基岩将生成在这个 Y 坐标。
island-height: 63



# 玩家最多可以删除自己岛屿的次数
max-delete-times: 3

# 传送点设置权限配置
# 是否允许玩家在下界使用 /is sethome 设置传送点
allow-sethome-in-nether: true
# 是否允许玩家在末地使用 /is sethome 设置传送点
allow-sethome-in-end: true

# 权限提示消息冷却时间（毫秒），防止玩家在快速触发（如踩踏耕地、触发压力板）时被刷屏
permission-message-cooldown: 1000
