name: StarMSkyblock
version: '${version}'

main: team.starm.starmskyblock.StarMSkyblock
api-version: '26.1.2'
load: POSTWORLD
softdepend: [ PlaceholderAPI, WorldEdit, TrMenu, Vault ]

authors: [ BrokenDream_Star,DeepSeek,Gemini,Grok ]
website: https://starm.team/
description: StarM的空岛插件

commands:
  is:
    description: 空岛主命令
    usage: /is <create|spawn|border|help>
    permission: skyblock.is
  isadmin:
    description: 空岛管理员命令
    usage: /isadmin setradius <island-id> <radius>
    permission: skyblock.admin

permissions:
  skyblock.is:
    description: 允许玩家使用基础空岛命令
    default: true
  skyblock.admin:
    description: 允许玩家使用管理员空岛命令
    default: op
