# =============================================
# 岛屿默认设置配置
# =============================================
# 创建岛屿时，系统会读取此文件的值作为岛屿初始设置
# 之后玩家可通过命令或GUI修改自己岛屿的设置

# 是否允许PVP
pvp: true

# 是否允许其他玩家传送到该岛屿
tp: true

# 是否允许动物自然生成
animal_spawn: true

# 是否允许怪物自然生成
monster_spawn: true

# 是否允许刷怪笼生成生物
spawner_spawn: true

# 是否允许火势蔓延
fire_spread: true

# 是否允许末影人搬运方块
enderman_grief: false

# 是否允许恶魂火球破坏方块
ghast_fireball_grief: false

# 是否允许爬行者爆炸破坏
creeper_explosion: false

# 是否允许TNT爆炸破坏
tnt_explosion: true

# 是否允许凋灵破坏方块
wither_grief: false
