name: '菇菇嘎嘎'
description: '种植并砍伐诡异菌和绯红菌'
task_type: ITEM
request:
  1:
    types:
      - CRIMSON_STEM
    amount: 64
  2:
    types:
      - WARPED_STEM
    amount: 64
reward:
  money: 5000
  item:
    - material: RED_MUSHROOM
      amount: 1
    - material: BROWN_MUSHROOM
      amount: 1
