name: '下界刷石机'
description: '建造玄武岩刷石机并刷取一些下界方块'
task_required: []
task_type: BLOCK_BREAK
request:
  1:
    types:
      - BASALT
    amount: 128
  2:
    types:
      - NETHERRACK
    amount: 32
  3:
    types:
      - GLOWSTONE
    amount: 8
reward:
  item:
    - material: BLAZE_SPAWN_EGG
      amount: 2
    - material: SPAWNER
      amount: 1
  command:
    - 'server: money give %player_name% 5000'
