name: '绝命毒师'
description: '种植下界疣然后酿造一些剧毒药水'
task_type: ITEM
request:
  1:
    types:
      - POTION
    amount: 3
    potion_type: POISON
reward:
  item:
    - material: WITHER_SKELETON_SPAWN_EGG
      amount: 2
  command:
    - 'server: money give %player_name% 10000'
