name: '农夫乐事'
description: '种植一些农作物'
task_required: Chapter1/Mission1_2
task_type: BLOCK_PLACE
request:
  1:
    types:
      - WHEAT
    amount: 16
  2:
    types:
      - CARROTS
    amount: 16
reward:
  command:
    - 'server: money %player_name% 2000'
