name: '空岛 启动!'
description: '制造刷石机并刷取一些圆石'
task_required: []
task_type: BLOCK_BREAK
request:
  1:
    types:
      - COBBLESTONE
    amount: 128
only-natural: true
reward:
  command:
    - 'server: money give %player_name% 1000'
    - 'server: lce itemcollection give skyblockreward task1_1_1 %player_name%'
