name: '会掉树苗吗?'
description: '种植并砍伐一些树'
task_type: ITEM
request:
  1:
    types:
      - OAK_LOG
      - SPRUCE_LOG
      - BIRCH_LOG
      - JUNGLE_LOG
      - ACACIA_LOG
      - DARK_OAK_LOG
      - MANGROVE_LOG
      - CHERRY_LOG
      - PALE_OAK_LOG
      - BAMBOO_BLOCK
    amount: 32
reward:
  money: 1000
  command:
    - 'server: lce itemcollection give skyblockreward task1_2_1 %player_name%'
