import re

# Suffix-based item patterns (any material ending with these is an item)
ITEM_SUFFIXES = (
    "_SPAWN_EGG", "_BOAT", "_CHEST_BOAT", "_RAFT", "_CHEST_RAFT",
    "_MINECART",
    "_SWORD", "_AXE", "_PICKAXE", "_SHOVEL", "_HOE",
    "_HELMET", "_CHESTPLATE", "_LEGGINGS", "_BOOTS",
    "_HORSE_ARMOR",
    "_SMITHING_TEMPLATE", "_POTTERY_SHERD",
    "_DYE",
    "_SPEAR",
)

# Prefix-based item patterns
ITEM_PREFIXES = ("MUSIC_DISC_", "LEGACY_",)

# Exact name items (not blocks)
EXACT_ITEMS = {
    "SADDLE", "ELYTRA", "SHIELD", "FISHING_ROD", "FLINT_AND_STEEL", "SHEARS",
    "BOW", "CROSSBOW", "TRIDENT", "MACE", "BRUSH",
    "LEAD", "COMPASS", "RECOVERY_COMPASS", "CLOCK", "SPYGLASS", "GOAT_HORN",
    "BOWL", "STICK", "BLAZE_ROD", "BREEZE_ROD", "ENDER_PEARL", "ENDER_EYE",
    "EXPERIENCE_BOTTLE", "FIREWORK_ROCKET", "FIREWORK_STAR",
    "ENCHANTED_BOOK", "NAME_TAG",
    "NAUTILUS_SHELL", "HEART_OF_THE_SEA", "TOTEM_OF_UNDYING",
    "BOOK", "WRITABLE_BOOK", "WRITTEN_BOOK",
    "PAPER", "MAP", "FILLED_MAP", "KNOWLEDGE_BOOK",
    "DEBUG_STICK", "CARROT_ON_A_STICK", "WARPED_FUNGUS_ON_A_STICK",
    "DRAGON_BREATH", "GLASS_BOTTLE", "STRING", "FEATHER", "GUNPOWDER", "FLINT",
    "LEATHER", "RABBIT_HIDE", "RABBIT_FOOT", "SCUTE", "AMETHYST_SHARD",
    "PHANTOM_MEMBRANE", "PRISMARINE_SHARD", "PRISMARINE_CRYSTALS",
    "RAW_IRON", "RAW_GOLD", "RAW_COPPER",
    "IRON_INGOT", "GOLD_INGOT", "COPPER_INGOT", "NETHERITE_INGOT",
    "NETHERITE_SCRAP", "DIAMOND", "EMERALD", "QUARTZ", "LAPIS_LAZULI",
    "COAL", "CHARCOAL", "IRON_NUGGET", "GOLD_NUGGET",
    "APPLE", "BREAD", "COOKED_BEEF", "COOKED_PORKCHOP", "COOKED_CHICKEN",
    "COOKED_COD", "COOKED_SALMON", "COOKED_MUTTON", "COOKED_RABBIT",
    "BEEF", "PORKCHOP", "CHICKEN", "COD", "SALMON", "MUTTON", "RABBIT",
    "DRIED_KELP", "PUMPKIN_PIE", "COOKIE", "CHORUS_FRUIT", "POPPED_CHORUS_FRUIT",
    "SWEET_BERRIES", "GLOW_BERRIES", "MELON_SLICE",
    "CARROT", "POTATO", "BEETROOT", "WHEAT_SEEDS",
    "BEETROOT_SEEDS", "MELON_SEEDS", "PUMPKIN_SEEDS",
    "TORCHFLOWER_SEEDS", "PITCHER_POD",
    "WHEAT",
    "BUCKET", "WATER_BUCKET", "LAVA_BUCKET", "MILK_BUCKET", "HONEY_BOTTLE",
    "PUFFERFISH_BUCKET", "SALMON_BUCKET", "COD_BUCKET", "TROPICAL_FISH_BUCKET",
    "AXOLOTL_BUCKET", "TADPOLE_BUCKET", "POWDER_SNOW_BUCKET",
    "BONE_MEAL", "EGG", "SNOWBALL", "ARMOR_STAND", "PAINTING",
    "ITEM_FRAME", "GLOW_ITEM_FRAME",
    "INK_SAC", "GLOW_INK_SAC", "COCOA_BEANS", "BONE",
    "DISC_FRAGMENT_5", "NETHER_STAR", "SHULKER_SHELL",
    "POTION", "LINGERING_POTION", "SPLASH_POTION",
    "RABBIT_STEW", "BEETROOT_SOUP", "MUSHROOM_STEW", "SUSPICIOUS_STEW",
    "BAKED_POTATO", "POISONOUS_POTATO", "GOLDEN_CARROT",
    "ROTTEN_FLESH", "SPIDER_EYE", "FERMENTED_SPIDER_EYE", "MAGMA_CREAM",
    "GHAST_TEAR", "GLISTERING_MELON_SLICE", "BLAZE_POWDER", "SUGAR",
    "SLIME_BALL", "GLOWSTONE_DUST", "REDSTONE", "CLAY_BALL", "BRICK",
    "NETHER_BRICK", "HONEYCOMB", "PUFFERFISH", "TROPICAL_FISH",
    "TURTLE_HELMET", "TURTLE_SCUTE", "ARMADILLO_SCUTE",
    "WOLF_ARMOR", "ECHO_SHARD", "FIRE_CHARGE",
    "GOLDEN_APPLE", "ENCHANTED_GOLDEN_APPLE",
    "OMINOUS_BOTTLE", "TRIAL_KEY", "OMINOUS_TRIAL_KEY", "WIND_CHARGE",
    "FLOWER_BANNER_PATTERN", "CREEPER_BANNER_PATTERN", "SKULL_BANNER_PATTERN",
    "MOJANG_BANNER_PATTERN", "GLOBE_BANNER_PATTERN", "PIGLIN_BANNER_PATTERN",
    "FLOW_BANNER_PATTERN", "GUSTER_BANNER_PATTERN",
    "FIELD_MASONED_BANNER_PATTERN", "BORDURE_INDENTED_BANNER_PATTERN",
    "TIPPED_ARROW", "SPECTRAL_ARROW", "ARROW",
    # Materials that are blocks but already in the config with different names
    "OBSIDIAN", "CRYING_OBSIDIAN",
    "NETHERITE_BLOCK",
    "BROWN_MUSHROOM_BLOCK", "RED_MUSHROOM_BLOCK", "MUSHROOM_STEM",
    "SNOW",
    "BRICKS",
    "SHORT_GRASS",
    "LILY_PAD", "COBWEB", "SEA_PICKLE",
    "HAY_BLOCK", "JACK_O_LANTERN", "CARVED_PUMPKIN",
    "BREWING_STAND", "FLOWER_POT", "LADDER",
    "PEARLESCENT_FROGLIGHT", "OCHRE_FROGLIGHT", "VERDANT_FROGLIGHT",
    "DRIED_GHAST",
    "TURTLE_EGG",
    "STONE_SPEAR",
    "COPPER_SPEAR",
    "IRON_SPEAR", "GOLDEN_SPEAR", "DIAMOND_SPEAR", "NETHERITE_SPEAR",
    "WOODEN_SPEAR",
    "COPPER_HORSE_ARMOR", "DIAMOND_HORSE_ARMOR", "GOLDEN_HORSE_ARMOR",
    "IRON_HORSE_ARMOR", "LEATHER_HORSE_ARMOR", "NETHERITE_HORSE_ARMOR",
    "COPPER_NAUTILUS_ARMOR", "IRON_NAUTILUS_ARMOR",
    "GOLDEN_NAUTILUS_ARMOR", "DIAMOND_NAUTILUS_ARMOR",
    "NETHERITE_NAUTILUS_ARMOR",
    "COPPER_GOLEM_STATUE",
    "EXPOSED_COPPER_GOLEM_STATUE",
    "WEATHERED_COPPER_GOLEM_STATUE",
    "OXIDIZED_COPPER_GOLEM_STATUE",
    "WAXED_COPPER_GOLEM_STATUE",
    "WAXED_EXPOSED_COPPER_GOLEM_STATUE",
    "WAXED_WEATHERED_COPPER_GOLEM_STATUE",
    "WAXED_OXIDIZED_COPPER_GOLEM_STATUE",
    "HAPPY_GHAST_SPAWN_EGG",
    "CAMEL_HUSK_SPAWN_EGG",
    "ZOMBIE_NAUTILUS_SPAWN_EGG",
    "PARCHED_SPAWN_EGG",
    "NAUTILUS_SPAWN_EGG",
    "BOGGED_SPAWN_EGG",
    "CREAKING_SPAWN_EGG",
    "COPPER_GOLEM_SPAWN_EGG",
    "ENDER_DRAGON_SPAWN_EGG",
    "IRON_GOLEM_SPAWN_EGG",
    "SNOW_GOLEM_SPAWN_EGG",
    # Dyes
    "WHITE_DYE", "ORANGE_DYE", "MAGENTA_DYE", "LIGHT_BLUE_DYE",
    "YELLOW_DYE", "LIME_DYE", "PINK_DYE", "GRAY_DYE", "LIGHT_GRAY_DYE",
    "CYAN_DYE", "PURPLE_DYE", "BLUE_DYE", "BROWN_DYE", "GREEN_DYE",
    "RED_DYE", "BLACK_DYE",
    # HARNESS items
    "WHITE_HARNESS", "ORANGE_HARNESS", "MAGENTA_HARNESS", "LIGHT_BLUE_HARNESS",
    "YELLOW_HARNESS", "LIME_HARNESS", "PINK_HARNESS", "GRAY_HARNESS",
    "LIGHT_GRAY_HARNESS", "CYAN_HARNESS", "PURPLE_HARNESS", "BLUE_HARNESS",
    "BROWN_HARNESS", "GREEN_HARNESS", "RED_HARNESS", "BLACK_HARNESS",
    # EGGS (decorated pot eggs)
    "BLUE_EGG", "BROWN_EGG",
}

# Technical blocks (blocks that exist in the game but shouldn't be in config)
TECHNICAL_BLOCKS = {
    "AIR", "CAVE_AIR", "VOID_AIR",
    "BUBBLE_COLUMN", "LAVA", "WATER",
    "PISTON_HEAD", "MOVING_PISTON",
    "FIRE", "SOUL_FIRE",
    "NETHER_PORTAL", "END_PORTAL", "END_GATEWAY",
    "POTTED_OAK_SAPLING", "POTTED_SPRUCE_SAPLING", "POTTED_BIRCH_SAPLING",
    "POTTED_JUNGLE_SAPLING", "POTTED_ACACIA_SAPLING", "POTTED_CHERRY_SAPLING",
    "POTTED_DARK_OAK_SAPLING", "POTTED_PALE_OAK_SAPLING",
    "POTTED_MANGROVE_PROPAGULE",
    "POTTED_FERN", "POTTED_DANDELION", "POTTED_POPPY", "POTTED_BLUE_ORCHID",
    "POTTED_ALLIUM", "POTTED_AZURE_BLUET", "POTTED_RED_TULIP",
    "POTTED_ORANGE_TULIP", "POTTED_WHITE_TULIP", "POTTED_PINK_TULIP",
    "POTTED_OXEYE_DAISY", "POTTED_CORNFLOWER", "POTTED_LILY_OF_THE_VALLEY",
    "POTTED_WITHER_ROSE", "POTTED_TORCHFLOWER",
    "POTTED_BROWN_MUSHROOM", "POTTED_RED_MUSHROOM",
    "POTTED_CRIMSON_FUNGUS", "POTTED_WARPED_FUNGUS",
    "POTTED_CRIMSON_ROOTS", "POTTED_WARPED_ROOTS",
    "POTTED_AZALEA_BUSH", "POTTED_FLOWERING_AZALEA_BUSH",
    "POTTED_BAMBOO", "POTTED_DEAD_BUSH",
    "POTTED_CACTUS", "POTTED_OPEN_EYEBLOSSOM", "POTTED_CLOSED_EYEBLOSSOM",
    "KELP_PLANT", "BAMBOO_SAPLING",
    "WATER_CAULDRON", "LAVA_CAULDRON", "POWDER_SNOW_CAULDRON",
    "BIG_DRIPLEAF_STEM",
    "ATTACHED_MELON_STEM", "ATTACHED_PUMPKIN_STEM",
    "MELON_STEM", "PUMPKIN_STEM",
    "TRIPWIRE", "POWDER_SNOW",
    "TWISTING_VINES_PLANT", "WEEPING_VINES_PLANT",
    "FROSTED_ICE",
    "PUMPKIN_STEM", "MELON_STEM",
    "COMMAND_BLOCK", "REPEATING_COMMAND_BLOCK", "CHAIN_COMMAND_BLOCK",
    "STRUCTURE_BLOCK", "STRUCTURE_VOID", "JIGSAW",
    "BARRIER", "LIGHT",
    "TEST_BLOCK", "TEST_INSTANCE_BLOCK",
    "REINFORCED_DEEPSLATE",
    "PETRIFIED_OAK_SLAB",
    "END_PORTAL_FRAME",
    "BEDROCK",
    "CAKE",
    "CAULDRON",
    "FROGSPAWN",
    "INFESTED_STONE", "INFESTED_COBBLESTONE",
    "INFESTED_STONE_BRICKS", "INFESTED_MOSSY_STONE_BRICKS",
    "INFESTED_CRACKED_STONE_BRICKS", "INFESTED_CHISELED_STONE_BRICKS",
    "INFESTED_DEEPSLATE",
    "DIRT_PATH",
    "SOUL_TORCH", "SOUL_WALL_TORCH",
    "REDSTONE_WALL_TORCH",
    "WALL_TORCH",
    "COPPER_WALL_TORCH",
    "COPPER_TORCH",
    # Wall sign variants (same as regular sign, just facing direction)
    "ACACIA_WALL_SIGN", "BAMBOO_WALL_SIGN", "BIRCH_WALL_SIGN",
    "CHERRY_WALL_SIGN", "CRIMSON_WALL_SIGN", "DARK_OAK_WALL_SIGN",
    "JUNGLE_WALL_SIGN", "MANGROVE_WALL_SIGN", "OAK_WALL_SIGN",
    "PALE_OAK_WALL_SIGN", "SPRUCE_WALL_SIGN", "WARPED_WALL_SIGN",
    # Hanging wall sign variants
    "ACACIA_WALL_HANGING_SIGN", "BAMBOO_WALL_HANGING_SIGN",
    "BIRCH_WALL_HANGING_SIGN", "CHERRY_WALL_HANGING_SIGN",
    "CRIMSON_WALL_HANGING_SIGN", "DARK_OAK_WALL_HANGING_SIGN",
    "JUNGLE_WALL_HANGING_SIGN", "MANGROVE_WALL_HANGING_SIGN",
    "OAK_WALL_HANGING_SIGN", "PALE_OAK_WALL_HANGING_SIGN",
    "SPRUCE_WALL_HANGING_SIGN", "WARPED_WALL_HANGING_SIGN",
    # Wall banners (same as banner, just wall variant)
    "WHITE_WALL_BANNER", "ORANGE_WALL_BANNER", "MAGENTA_WALL_BANNER",
    "LIGHT_BLUE_WALL_BANNER", "YELLOW_WALL_BANNER", "LIME_WALL_BANNER",
    "PINK_WALL_BANNER", "GRAY_WALL_BANNER", "LIGHT_GRAY_WALL_BANNER",
    "CYAN_WALL_BANNER", "PURPLE_WALL_BANNER", "BLUE_WALL_BANNER",
    "BROWN_WALL_BANNER", "GREEN_WALL_BANNER", "RED_WALL_BANNER",
    "BLACK_WALL_BANNER",
    # Wall heads
    "CREEPER_WALL_HEAD", "DRAGON_WALL_HEAD", "PIGLIN_WALL_HEAD",
    "PLAYER_WALL_HEAD", "SKELETON_WALL_SKULL", "WITHER_SKELETON_WALL_SKULL",
    "ZOMBIE_WALL_HEAD",
    # Wall coral fans (same as regular fan, just on wall)
    "TUBE_CORAL_WALL_FAN", "BRAIN_CORAL_WALL_FAN", "BUBBLE_CORAL_WALL_FAN",
    "FIRE_CORAL_WALL_FAN", "HORN_CORAL_WALL_FAN",
    "DEAD_TUBE_CORAL_WALL_FAN", "DEAD_BRAIN_CORAL_WALL_FAN",
    "DEAD_BUBBLE_CORAL_WALL_FAN", "DEAD_FIRE_CORAL_WALL_FAN",
    "DEAD_HORN_CORAL_WALL_FAN",
    # BUNDLE items (not blocks)
    "BUNDLE", "WHITE_BUNDLE", "ORANGE_BUNDLE", "MAGENTA_BUNDLE",
    "LIGHT_BLUE_BUNDLE", "YELLOW_BUNDLE", "LIME_BUNDLE", "PINK_BUNDLE",
    "GRAY_BUNDLE", "LIGHT_GRAY_BUNDLE", "CYAN_BUNDLE", "PURPLE_BUNDLE",
    "BLUE_BUNDLE", "BROWN_BUNDLE", "GREEN_BUNDLE", "RED_BUNDLE",
    "BLACK_BUNDLE",
    # CANDLE_CAKE blocks (these are technical combined blocks)
    "CANDLE_CAKE", "WHITE_CANDLE_CAKE", "ORANGE_CANDLE_CAKE",
    "MAGENTA_CANDLE_CAKE", "LIGHT_BLUE_CANDLE_CAKE", "YELLOW_CANDLE_CAKE",
    "LIME_CANDLE_CAKE", "PINK_CANDLE_CAKE", "GRAY_CANDLE_CAKE",
    "LIGHT_GRAY_CANDLE_CAKE", "CYAN_CANDLE_CAKE", "PURPLE_CANDLE_CAKE",
    "BLUE_CANDLE_CAKE", "BROWN_CANDLE_CAKE", "GREEN_CANDLE_CAKE",
    "RED_CANDLE_CAKE", "BLACK_CANDLE_CAKE",
    # Items we don't want as config entries
    "COMMAND_BLOCK_MINECART",
    # Duplicate with existing config: CRYING_OBSIDIAN is already in 末地扩展
    # CHAIN is already in 其他实用方块
    "CHAIN",
    # Bridges (not real blocks)
    "WOODEN_SPEAR",
}

def is_block(name):
    """Determine if a Material is a block (not an item, not technical)."""
    # Legacy materials are skipped
    if name.upper().startswith("LEGACY_"):
        return False

    # Check suffixes
    for suffix in ITEM_SUFFIXES:
        if name.endswith(suffix):
            return False

    # Check prefixes
    for prefix in ITEM_PREFIXES:
        if name.startswith(prefix):
            return False

    # Check exact names
    if name in EXACT_ITEMS:
        return False

    # Everything else is a block
    return True

# Read current config
with open('src/main/resources/block-values.yml', 'r') as f:
    config_text = f.read()

# Extract material names from config
config_materials = set()
for line in config_text.split('\n'):
    m = re.match(r'^\s+([A-Z_]+):\s+\d+', line)
    if m:
        config_materials.add(m.group(1))

# Read all materials from enum
with open('/tmp/all_materials.txt', 'r') as f:
    all_materials = [l.strip() for l in f if l.strip()]

# Filter to blocks
block_materials = set(n for n in all_materials if is_block(n))

# Filter out technical blocks
real_blocks = block_materials - TECHNICAL_BLOCKS
missing = sorted(real_blocks - config_materials)
# Also find blocks in config that are NOT in the enum
extra_in_config = sorted(config_materials - real_blocks - TECHNICAL_BLOCKS)

print(f"Total enum constants: {len(all_materials)}")
print(f"Identified as blocks: {len(block_materials)}")
print(f"Technical blocks excluded: {len(TECHNICAL_BLOCKS)}")
print(f"Currently configured: {len(config_materials)}")
print(f"Missing blocks to add: {len(missing)}")
if extra_in_config:
    print(f"WARNING: Config has {len(extra_in_config)} entries not in block enum:")
    for m in extra_in_config[:10]:
        print(f"  {m}")
print()
print("=== MISSING BLOCKS ===")
for m in missing:
    print(m)