name: '无限岩浆'
description: '当方块上方为岩浆源 下方为滴水石锥 且滴水石锥正下方为炼药锅时 炼药锅会缓慢装满岩浆'
task_required: []
task_type: ITEM
request:
  1:
    types:
      - LAVA_BUCKET
    amount: 8
reward:
  item:
    - material: FLINT_AND_STEEL
      amount: 1
    - material: OBSIDIAN
      amount: 14
  command:
    - 'server: money %player_name% 5000'
