name: '铁器时代'
description: '升级你的刷石机 使得刷石机可以生成铁矿'
task_type: BLOCK_BREAK
request:
  1:
    types:
      - IRON_ORE
    amount: 32
only-natural: true
reward:
  money: 2000
  item:
    - material: POINTED_DRIPSTONE
      amount: 1
    - material: POINTED_BLOCK
      amount: 1
