name: '屠夫'
description: '繁殖并击杀一些动物'
task_type: ENTITY_KILL
request:
  1:
    types:
      - SLEEP
    amount: 8
  2:
    types:
      - COW
    amount: 8
reward:
  item:
    - material: PIG_SPAWN_EGG
      amount: 2
