name: '钟乳石'
description: '当滴水石块上方为水源 下方为滴水石锥 且滴水石锥正下方为非流体方块时 滴水石锥会生长'
task_type: BLOCK_BREAK
request:
  1:
    types:
      - POINTED_DRIPSTONE
    amount: 1
reward:
  money: 3000
  item:
    - material: LAVA_BUCKET
      amount: 2
    - material: POINTED_DRIPSTONE
      amount: 8